language: php
script: php vendor/phpunit/phpunit/composer/bin/phpunit --verbose --coverage-text

php:
  - 5.3
  - 5.4

before_script:
  - "git clone --branch=master git://github.com/EllisLab/CodeIgniter.git codeigniter"
  - "cp -R codeigniter/* ../CI-Code-Generator/"
  - "rm -rf codeigniter/"
  - "curl -s http://getcomposer.org/installer | php"
  - "php composer.phar --dev install"

after_script:
  - "php vendor/phpunit/phpunit/composer/bin/phpunit --testdox"
